USE [master]
GO

/****** Object:  Database [OrderDb]    Script Date: 8/23/2026 11:32:55 AM ******/
CREATE DATABASE [OrderDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OrderDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\OrderDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OrderDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\OrderDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OrderDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OrderDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OrderDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OrderDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OrderDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OrderDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [OrderDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [OrderDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OrderDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OrderDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OrderDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OrderDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OrderDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OrderDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OrderDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OrderDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [OrderDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OrderDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OrderDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OrderDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OrderDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OrderDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [OrderDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OrderDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OrderDb] SET  MULTI_USER 
GO

ALTER DATABASE [OrderDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OrderDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OrderDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OrderDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OrderDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OrderDb] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [OrderDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [OrderDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [OrderDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [OrderDb] SET  READ_WRITE 
GO

